#server (eureka 默认端口为8761)
server:
  port: 8700
#服务名
spring:
  application:
    name: eureka-server1
eureka:
  client:
    #服务地址
    service-url:
      #这里设置服务地址8701，注意peer1的端口是8700
      defaultZone: http://localhost:8701/eureka/

