spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_logService1
          #以lb://开头(lb代表从注册中心获取服务),后面接的就是你需要转发到的服务名称
          uri: lb://logService1
          predicates:
            - Path=/logService1/**
        - id: route_logService2
          uri: lb://logService2
          predicates:
            - Path=/logService2/**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true